# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('favorite_authors', models.ManyToManyField(blank=True, related_name='_author_favorite_authors_+', to='crawler.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('published', models.DateField()),
                ('updated', models.DateField()),
                ('chapters', models.IntegerField()),
                ('rated', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=15)),
                ('genre1', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('genre2', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('character1', models.CharField(blank=True, default=None, max_length=31, null=True)),
                ('character2', models.CharField(blank=True, default=None, max_length=31, null=True)),
                ('character3', models.CharField(blank=True, default=None, max_length=31, null=True)),
                ('character4', models.CharField(blank=True, default=None, max_length=31, null=True)),
                ('reviews', models.IntegerField()),
                ('story_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crawler.Author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='favorite_stories',
            field=models.ManyToManyField(blank=True, to='crawler.Story'),
        ),
    ]
