# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_author',
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crawler.Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='favorite_stories',
            field=models.ManyToManyField(blank=True, related_name='_author_favorite_stories_+', to='crawler.Story'),
        ),
    ]
