# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20170312_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='character1',
            field=models.CharField(blank=True, default=None, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='character2',
            field=models.CharField(blank=True, default=None, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='character3',
            field=models.CharField(blank=True, default=None, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='character4',
            field=models.CharField(blank=True, default=None, max_length=63, null=True),
        ),
    ]
